export const bitcoinTypes = {
  AWAITING_BITCOIN : "AWAITING_BITCOIN",
  SET_BITCOIN : "SET_BITCOIN",
  BITCOIN_REJECTED : "BITCOIN_REJECTED",
  GET_BITCOIN: "GET_BITCOIN"
}
export const userTypes = {
  AWAITING_USER: "AWAITING_USER",
  SET_USER: "SET_USER",
  USER_REJECTED: "USER_REJECTED",
  GET_USER: "GET_USER"
}

export const GET_DATA = "GET_DATA"